# Generated by Django 5.0.7 on 2026-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_attendance_course_teacher_assignedclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedclass',
            name='camera',
        ),
        migrations.AddField(
            model_name='assignedclass',
            name='cameras',
            field=models.ManyToManyField(blank=True, help_text='Cameras attached to this class', related_name='assigned_classes', to='app1.cameraconfiguration'),
        ),
    ]
